// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFuN4kHQHhZNansoayTo14mSXhe92aMGg',
    appId: '1:158152103967:web:8723f2474f1394fbb69d2a',
    messagingSenderId: '158152103967',
    projectId: 'chating-app-5fb7d',
    authDomain: 'chating-app-5fb7d.firebaseapp.com',
    storageBucket: 'chating-app-5fb7d.appspot.com',
    measurementId: 'G-VYEE5V83W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEfkMrqFHjN9Ii707mMJ_x3xyUp69Pu8A',
    appId: '1:158152103967:android:881fd48a8eafeafbb69d2a',
    messagingSenderId: '158152103967',
    projectId: 'chating-app-5fb7d',
    storageBucket: 'chating-app-5fb7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByqxC-TZNKp7I-mci_5CXihI_jRmqDajU',
    appId: '1:158152103967:ios:23adf66331faad15b69d2a',
    messagingSenderId: '158152103967',
    projectId: 'chating-app-5fb7d',
    storageBucket: 'chating-app-5fb7d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByqxC-TZNKp7I-mci_5CXihI_jRmqDajU',
    appId: '1:158152103967:ios:343480e132c9301fb69d2a',
    messagingSenderId: '158152103967',
    projectId: 'chating-app-5fb7d',
    storageBucket: 'chating-app-5fb7d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
